"""Map WTO RTA party names → (ISO-ish code, Chinese name).

WTO RTA names use forms like "Korea, Republic of", "Moldova, Republic of",
"United States", "European Union", "EFTA", "ASEAN". We normalise these to a
stable code (unifying with the curated seed which uses ISO codes) and a Chinese
name. Unmapped parties fall back to the English string for both.
"""
from __future__ import annotations

# code, zh
COUNTRY_MAP: dict[str, tuple[str, str]] = {
    "united states": ("US", "美國"),
    "united states of america": ("US", "美國"),
    "china": ("CN", "中國"),
    "japan": ("JP", "日本"),
    "korea, republic of": ("KR", "韓國"),
    "republic of korea": ("KR", "韓國"),
    "korea": ("KR", "韓國"),
    "taiwan": ("TW", "台灣"),
    "separate customs territory of taiwan, penghu, kinmen and matsu": ("TW", "台灣"),
    "chinese taipei": ("TW", "台灣"),
    "india": ("IN", "印度"),
    "european union": ("EU", "歐盟"),
    "european communities": ("EU", "歐盟"),
    "efta": ("EFTA", "歐洲自由貿易聯盟"),
    "european free trade association": ("EFTA", "歐洲自由貿易聯盟"),
    "european free trade association (efta)": ("EFTA", "歐洲自由貿易聯盟"),
    "asean": ("ASEAN", "東協"),
    "association of southeast asian nations": ("ASEAN", "東協"),
    "association of southeast asian nations (asean)": ("ASEAN", "東協"),
    "united kingdom": ("GB", "英國"),
    "australia": ("AU", "澳洲"),
    "new zealand": ("NZ", "紐西蘭"),
    "canada": ("CA", "加拿大"),
    "mexico": ("MX", "墨西哥"),
    "brazil": ("BR", "巴西"),
    "argentina": ("AR", "阿根廷"),
    "chile": ("CL", "智利"),
    "peru": ("PE", "秘魯"),
    "colombia": ("CO", "哥倫比亞"),
    "uruguay": ("UY", "烏拉圭"),
    "paraguay": ("PY", "巴拉圭"),
    "ecuador": ("EC", "厄瓜多"),
    "bolivia": ("BO", "玻利維亞"),
    "bolivia, plurinational state of": ("BO", "玻利維亞"),
    "venezuela": ("VE", "委內瑞拉"),
    "venezuela, bolivarian republic of": ("VE", "委內瑞拉"),
    "singapore": ("SG", "新加坡"),
    "malaysia": ("MY", "馬來西亞"),
    "thailand": ("TH", "泰國"),
    "viet nam": ("VN", "越南"),
    "vietnam": ("VN", "越南"),
    "indonesia": ("ID", "印尼"),
    "philippines": ("PH", "菲律賓"),
    "brunei darussalam": ("BN", "汶萊"),
    "brunei": ("BN", "汶萊"),
    "cambodia": ("KH", "柬埔寨"),
    "lao people's democratic republic": ("LA", "寮國"),
    "laos": ("LA", "寮國"),
    "myanmar": ("MM", "緬甸"),
    "hong kong, china": ("HK", "香港"),
    "macao, china": ("MO", "澳門"),
    "switzerland": ("CH", "瑞士"),
    "norway": ("NO", "挪威"),
    "iceland": ("IS", "冰島"),
    "liechtenstein": ("LI", "列支敦斯登"),
    "turkey": ("TR", "土耳其"),
    "türkiye": ("TR", "土耳其"),
    "russian federation": ("RU", "俄羅斯"),
    "russia": ("RU", "俄羅斯"),
    "ukraine": ("UA", "烏克蘭"),
    "moldova, republic of": ("MD", "摩爾多瓦"),
    "moldova": ("MD", "摩爾多瓦"),
    "georgia": ("GE", "喬治亞"),
    "armenia": ("AM", "亞美尼亞"),
    "azerbaijan": ("AZ", "亞塞拜然"),
    "kazakhstan": ("KZ", "哈薩克"),
    "kyrgyz republic": ("KG", "吉爾吉斯"),
    "uzbekistan": ("UZ", "烏茲別克"),
    "tajikistan": ("TJ", "塔吉克"),
    "israel": ("IL", "以色列"),
    "jordan": ("JO", "約旦"),
    "egypt": ("EG", "埃及"),
    "morocco": ("MA", "摩洛哥"),
    "tunisia": ("TN", "突尼西亞"),
    "saudi arabia": ("SA", "沙烏地阿拉伯"),
    "united arab emirates": ("AE", "阿聯酋"),
    "qatar": ("QA", "卡達"),
    "kuwait": ("KW", "科威特"),
    "bahrain": ("BH", "巴林"),
    "oman": ("OM", "阿曼"),
    "gulf cooperation council (gcc)": ("GCC", "海灣合作委員會"),
    "gulf cooperation council": ("GCC", "海灣合作委員會"),
    "south africa": ("ZA", "南非"),
    "nigeria": ("NG", "奈及利亞"),
    "kenya": ("KE", "肯亞"),
    "mauritius": ("MU", "模里西斯"),
    "pakistan": ("PK", "巴基斯坦"),
    "bangladesh": ("BD", "孟加拉"),
    "sri lanka": ("LK", "斯里蘭卡"),
    "nepal": ("NP", "尼泊爾"),
    "mongolia": ("MN", "蒙古"),
    "iceland, liechtenstein": ("EFTA", "歐洲自由貿易聯盟"),
    "costa rica": ("CR", "哥斯大黎加"),
    "panama": ("PA", "巴拿馬"),
    "guatemala": ("GT", "瓜地馬拉"),
    "honduras": ("HN", "宏都拉斯"),
    "el salvador": ("SV", "薩爾瓦多"),
    "nicaragua": ("NI", "尼加拉瓜"),
    "dominican republic": ("DO", "多明尼加"),
    "mercosur": ("MERCOSUR", "南方共同市場"),
    "southern common market (mercosur)": ("MERCOSUR", "南方共同市場"),
    # EU member states (sometimes appear individually)
    "germany": ("DE", "德國"),
    "france": ("FR", "法國"),
    "italy": ("IT", "義大利"),
    "spain": ("ES", "西班牙"),
    "netherlands": ("NL", "荷蘭"),
    "belgium": ("BE", "比利時"),
    "poland": ("PL", "波蘭"),
    "sweden": ("SE", "瑞典"),
    "austria": ("AT", "奧地利"),
    "denmark": ("DK", "丹麥"),
    "finland": ("FI", "芬蘭"),
    "ireland": ("IE", "愛爾蘭"),
    "portugal": ("PT", "葡萄牙"),
    "greece": ("GR", "希臘"),
}


def normalize_party(name: str) -> tuple[str, str, str]:
    """Return (code, en_name, zh_name) for a party name string."""
    en = name.strip()
    key = en.lower().strip()
    if key in COUNTRY_MAP:
        code, zh = COUNTRY_MAP[key]
        return code, en, zh
    # fallback: use cleaned english for all three
    return en, en, en
